### PR TITLE
Build GDAL from source for OSX Github build

### PR DESCRIPTION
**Pull request by tbarsballe**
This is a follow-on to https://github.com/geotools/geotools/pull/4636 , restoring the GDAL OSX build by building GDAL from source.

This'll likely need a couple passes to get right, the initial commit is just the first pass based on how I've built GDAL on Mac locally. In particular, the GDAL version is currently hardcoded, and could be moved to job configuration / a CI variable

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geotools.org/latest/developer/conventions/code/qa.html)).

### CODE REVIEW

**Comment by tbarsballe** [comment]
GDAL build is now succeeding after the latest commit, though it takes 30 minutes, which isn't great, but also isn't surprising. I wonder if there's a way we can cache this?

Tests are still getting skipped though:
```
Native library load failed.
[INFO] Running org.geotools.imageio.GeoSpatialImageReaderTest
java.lang.UnsatisfiedLinkError: no gdalalljni in java.library.path: [/Users/runner/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
```

Looks like the GDAL CMake build is installing `libgdalalljni.dylib` to `"${CMAKE_INSTALL_PREFIX}/share/java"`
CMAKE_INSTALL_PREFIX is configurable, but shared by the whole gdal build, so the easiest solution is probably a symlink or modifying the java library path

**Comment by tbarsballe** [comment]
Looks like GItHub actions is [having some trouble](https://www.githubstatus.com/incidents/lfrlwdg67fn8). Seems to be resolved now, retrying...

File: .github/workflows/macos.yml [hunk 1]
```diff
@@ -18,6 +25,33 @@ jobs:
...
+        wget https://github.com/OSGeo/gdal/releases/download/v$OSX_GDAL_VERSION/gdal-$OSX_GDAL_VERSION.tar.gz
+        tar -xvf gdal-$OSX_GDAL_VERSION.tar.gz
+        cd gdal-$OSX_GDAL_VERSION
+        mkdir build
+        cd build
+        : # See https://github.com/OSGeo/gdal/issues/6949 (Java bindings) and https://github.com/OSGeo/gdal/pull/8226 (Arrow and Parquet)
+        cmake -DCMAKE_INSTALL_PREFIX=$GDAL_INSTALL_PATH -DCMAKE_BUILD_TYPE=Release -DBUILD_JAVA_BINDINGS=ON -DBUILD_PYTHON_BINDINGS=OFF ${CMAKE_OPTIONS} ..  
+        cmake --build .
+        cmake --build . --target install
+        ls $GDAL_INSTALL_PATH/lib/
```
Comment (tbarsballe) [inline .github/workflows/macos.yml:45]:
```
cmake
gdalplugins
jni
libgdal.35.3.9.0.dylib
libgdal.35.dylib
libgdal.dylib
pkgconfig
```

File: .github/workflows/macos.yml [hunk 2]
```diff
@@ -18,6 +25,33 @@ jobs:
...
+        ls $GDAL_INSTALL_PATH/lib/jni/
```
Comment (tbarsballe) [inline .github/workflows/macos.yml:46]:
```
libgdalalljni.dylib
```

**Review by tbarsballe — COMMENTED** [review]
I've captured some troubleshooting outputs from the runner.
At this point, I'm pretty convinced the JNI issue is with the OSX GDAL build itself, as it fails even using the included test jar.

There's also some suspicious stuff in the dylib files themself, but I don't understand what they're supposed to look like well enough to know if that actually represents an issue.

File: .github/workflows/macos.yml [hunk 3]
```diff
@@ -18,6 +25,28 @@ jobs:
...
+        cd gdal-$OSX_GDAL_VERSION
+        mkdir build
+        cd build
+        : # See https://github.com/OSGeo/gdal/issues/6949 (Java bindings) and https://github.com/OSGeo/gdal/pull/8226 (Arrow and Parquet)
+        cmake -DCMAKE_INSTALL_PREFIX=$GDAL_INSTALL_PATH -DCMAKE_BUILD_TYPE=Release -DBUILD_JAVA_BINDINGS=ON -DBUILD_PYTHON_BINDINGS=OFF ${CMAKE_OPTIONS} ..  
+        cmake --build .
+        cmake --build . --target install
+        ls /Users/runner/work/gdal/lib/jni/
+        ls /usr/lib/
+        otool -L $GDAL_INSTALL_PATH/lib/jni/libgdalalljni.dylib
```
[the remark this answers is not in the document]
Comment (tbarsballe) [reply .github/workflows/macos.yml:52]: Seems to be because of [this](https://stackoverflow.com/questions/70549365/why-are-my-system-libraries-and-frameworks-not-visible-in-macos-monterey) - all the system libraries are now virtual:
> As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache

No clue if that's a problem or not.

File: .github/workflows/macos.yml [hunk 4]
```diff
@@ -18,6 +25,34 @@ jobs:
...
+        ls $GDAL_INSTALL_PATH/lib/jni/
+        ls /usr/lib/
+        otool -L $GDAL_INSTALL_PATH/lib/libgdal.35.dylib
+        otool -l $GDAL_INSTALL_PATH/lib/libgdal.35.dylib
+        otool -L $GDAL_INSTALL_PATH/lib/libgdal.35.$OSX_GDAL_VERSION.dylib
+        otool -l $GDAL_INSTALL_PATH/lib/libgdal.35.$OSX_GDAL_VERSION.dylib
+        otool -L $GDAL_INSTALL_PATH/lib/jni/libgdalalljni.dylib
+        otool -l $GDAL_INSTALL_PATH/lib/jni/libgdalalljni.dylib
+        java --version
+        java -Djava.library.path=$DYLD_LIBRARY_PATH:$GDAL_INSTALL_PATH:/lib/jni/libgdalalljni.dylib -classpath $GDAL_INSTALL_PATH/share/java/gdal-$OSX_GDAL_VERSION.jar:$PWD/swig/java/build/apps gdalinfo
```
Comment (rouault) [inline .github/workflows/macos.yml:55]: isn't there a typo here with the ':' instead of a '/' between ``$GDAL_INSTALL_PATH`` and ``/lib/jni`` ? Furthermore you need to specify a directory name, not a filename. At least that's how it works for me
```suggestion
        java -Djava.library.path=$DYLD_LIBRARY_PATH:$GDAL_INSTALL_PATH/lib/jni -classpath $GDAL_INSTALL_PATH/share/java/gdal-$OSX_GDAL_VERSION.jar:$PWD/swig/java/build/apps gdalinfo
```

Comment (tbarsballe) [reply .github/workflows/macos.yml]: ... And in any case, the bindings are still failing with those changes.

I was planning on reporting this bindings failure as a bug to GDAL this week, once I find a little time to collect everything I've found here and clean it up into a proper report.

In advance of that, if you've got any other suggestions, I'm all ears.

**Comment by tbarsballe** [comment]
Alright, we've got a successful GDAL build with working (?) bindings, but now have a novel failure in gt-ogr:

```
testOptimizedEnvelope(org.geotools.data.ogr.jni.JniOGRDataStoreTest)  Time elapsed: 0.012 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: 'int org.gdal.osr.osrJNI.SpatialReference_ExportToWkt(long, org.gdal.osr.SpatialReference, java.lang.String[])'
	at org.gdal.osr.osrJNI.SpatialReference_ExportToWkt(Native Method)
	at org.gdal.osr.SpatialReference.ExportToWkt(SpatialReference.java:617)
	at org.gdal.osr.SpatialReference.ExportToWkt(SpatialReference.java:60)
	at org.geotools.data.ogr.jni.JniOGR.SpatialRefExportToWkt(JniOGR.java:730)
	at org.geotools.data.ogr.FeatureTypeMapper.getCRS(FeatureTypeMapper.java:310)
	at org.geotools.data.ogr.FeatureTypeMapper.getFeatureType(FeatureTypeMapper.java:72)
	at org.geotools.data.ogr.OGRFeatureSource.buildFeatureType(OGRFeatureSource.java:467)
	at org.geotools.data.ogr.OGRFeatureStore.buildFeatureType(OGRFeatureStore.java:122)
	at org.geotools.data.store.ContentFeatureSource.getAbsoluteSchema(ContentFeatureSource.java:339)
	at org.geotools.data.store.ContentFeatureSource.getSchema(ContentFeatureSource.java:308)
	at org.geotools.data.store.ContentFeatureSource.resolvePropertyNames(ContentFeatureSource.java:1146)
	at org.geotools.data.store.ContentFeatureSource.getBounds(ContentFeatureSource.java:376)
	at org.geotools.data.store.ContentFeatureSource.getBounds(ContentFeatureSource.java:364)
	at org.geotools.data.ogr.OGRDataStoreTest.testOptimizedEnvelope(OGRDataStoreTest.java:139)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by aaime** [comment]
Judging by the error, I'm guessing the java bindings we are using are outdated compared to the native library. 
If so, we need to either use a different method, or update the java bindings and figure out what GDAL versions are going to be supported by it, and if it's ok to switch to them (e.g., are the commonly available?)

**Comment by rouault** [comment]
> java.lang.UnsatisfiedLinkError: 'int org.gdal.osr.osrJNI.SpatialReference_ExportToWkt(long, org.gdal.osr.SpatialReference, java.lang.String[])'
> 	at org.gdal.osr.osrJNI.SpatialReference_ExportToWkt(Native Method)
> Judging by the error, I'm guessing the java bindings we are using are outdated compared to the native library.

yes, likely related to the addition of the optional "char **options = null" to https://github.com/OSGeo/gdal/blame/ca3d2de3164a2c6eb6459d4cf8b7870f226c8be6/swig/include/osr.i#L1086 that changed the Java method signature from a single osrJNI.SpatialReference_ExportToWkt to 2 methods:
```
swig/java/org/gdal/osr/osrJNI.java:  public final static native int SpatialReference_ExportToWkt__SWIG_0(long jarg1, SpatialReference jarg1_, String[] jarg2, java.util.Vector jarg3);
swig/java/org/gdal/osr/osrJNI.java:  public final static native int SpatialReference_ExportToWkt__SWIG_1(long jarg1, SpatialReference jarg1_, String[] jarg2);
```
That changed occured in GDAL 3.0, 5 years ago. GDAL 3.0 should be safe as a minimum baseline. That said, while we try to keep the public Java API backward compatible, that part of the bindings between the low-level SWIG generated Java part and native libgdalalljni is kind of an internal detail, and can be subject to changes we don't always realize as this is handled by SWIG.  Generally you want to deliver the combo gdal.jar + libgdalalljni to be sure things are fully consistent, but I understand this might be impractical here.

**Comment by tbarsballe** [comment]
Maven seems to be pulling the GDAL 2.2.0 Jar:
> [INFO] Downloading from osgeo: https://repo.osgeo.org/repository/release/org/gdal/gdal/2.2.0/gdal-2.2.0.pom
> [INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/gdal/gdal/2.2.0/gdal-2.2.0.pom
> [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/gdal/gdal/2.2.0/gdal-2.2.0.pom (1.1 kB at 356 kB/s)
> [INFO] Downloading from osgeo: https://repo.osgeo.org/repository/release/org/gdal/gdal/2.2.0/gdal-2.2.0.jar

And it seems like the (unsupported) ogr-jni module is [explicitly setting this version](https://github.com/geotools/geotools/blob/main/modules/unsupported/ogr/ogr-jni/pom.xml#L53-L55). The [vsi](https://github.com/geotools/geotools/blob/main/modules/unsupported/vsi/pom.xml) module does the same thing.

I expect this is overriding or otherwise fighting with the 3.7.0 jar we just built.

Meanwhile, imageio-gdal is pulling the dependency in transitively via imageio-exts; I'd hope that's handling things more dynamically? I've temporarily dropped `-T2` so imageio runs before the unsupported modules, so we can find out.

**Comment by aaime** [comment]
ImageIO-Ext is pulling a 3.2.0: https://github.com/geosolutions-it/imageio-ext/blob/master/pom.xml#L20

```
[INFO] -------< it.geosolutions.imageio-ext:imageio-ext-gdalframework >--------
[INFO] Building Image I/O-Extensions - GDAL Image IO Framework 1.4-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- dependency:3.6.0:tree (default-cli) @ imageio-ext-gdalframework ---
[INFO] it.geosolutions.imageio-ext:imageio-ext-gdalframework:jar:1.4-SNAPSHOT
[INFO] +- junit:junit:jar:4.13.1:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.gdal:gdal:jar:3.2.0:compile
[INFO] +- it.geosolutions.imageio-ext:imageio-ext-streams:jar:1.4-SNAPSHOT:compile
[INFO] +- it.geosolutions.imageio-ext:imageio-ext-utilities:jar:1.4-SNAPSHOT:compile
[INFO] +- it.geosolutions.imageio-ext:imageio-ext-geocore:jar:1.4-SNAPSHOT:compile
[INFO] |  +- javax.xml.bind:jaxb-api:jar:2.4.0-b180830.0359:compile
[INFO] |  +- org.glassfish.jaxb:jaxb-runtime:jar:2.4.0-b180830.0438:runtime
[INFO] |  |  +- org.glassfish.jaxb:txw2:jar:2.4.0-b180830.0438:runtime
[INFO] |  |  +- com.sun.istack:istack-commons-runtime:jar:3.0.7:runtime
[INFO] |  |  +- org.jvnet.staxex:stax-ex:jar:1.8:runtime
[INFO] |  |  \- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.15:runtime
[INFO] |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] +- javax.media:jai_core:jar:1.1.3:compile
[INFO] +- javax.media:jai_codec:jar:1.1.3:compile
[INFO] \- javax.media:jai_imageio:jar:1.1:compile
```

**Comment by tbarsballe** [comment]
And it looks like imageio-ext-gdal is succeeding with that configuration:
> Warning:  Tests run: 33, Failures: 0, Errors: 0, Skipped: 8

**Comment by tbarsballe** [comment]
Looks like the OGR module will definitely need upgrading, if I force it to use a newer GDAL we get a compilation error on [line 695](https://github.com/geotools/geotools/blob/main/modules/unsupported/ogr/ogr-jni/src/main/java/org/geotools/data/ogr/jni/JniOGR.java#L695):
```
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /Users/runner/work/geotools/geotools/modules/unsupported/ogr/ogr-jni/src/main/java/org/geotools/data/ogr/jni/JniOGR.java:[695,41] incompatible types: possible lossy conversion from long to int
[INFO] 1 error
```
Looking at the latest GDAL Javadoc, that error [is indeed accurate](https://gdal.org/java/org/gdal/ogr/Geometry.html#WkbSize())

This makes me wonder how the other OSes GDAL tests are working ... looks like linux is using GDAL 3.0.4, and WkbSize [appears to have been changed to a long around GDAL 3.3.0](https://github.com/OSGeo/gdal/commit/3798cbe48457b7127606931896549f26507469db)

Though in the end, this is an unsupported module, and imageio-ext *is* working on GDAL 3.9.0, so I don't thing this is critical

**Comment by tbarsballe** [comment]
Switching to 3.2.0 bindings with 3.9.0 native libs for ogr compiles, but fails tests - looks like the test failures are for a similar reason as the compilation  issue - incompatible numerical types.

```
Warning 1: Value '19 ' of field waypoints.ogr_string parsed incompletely to real 19.
Warning 1: Field string of width 255 truncated to 254.
Warning 6: Field date create as date field, though DateTime requested.
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 0 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 1 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 2 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 3 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 4 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 5 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 6 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 7 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 8 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 9 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 10 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 11 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 12 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 13 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 14 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 15 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 16 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 17 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 18 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 1.23456789012345678e+26 of field bigdecimal of feature 19 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Field name of width 255 truncated to 254.
Tests run: 28, Failures: 3, Errors: 3, Skipped: 0, Time elapsed: 1.203 sec <<< FAILURE! - in org.geotools.data.ogr.jni.JniOGRDataStoreTest
testShapefileComparison(org.geotools.data.ogr.jni.JniOGRDataStoreTest)  Time elapsed: 0.07 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.geotools.data.ogr.OGRDataStoreTest.assertFeatureTypeEquals(OGRDataStoreTest.java:269)
	at org.geotools.data.ogr.OGRDataStoreTest.testShapefileComparison(OGRDataStoreTest.java:203)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

testSchemaPop(org.geotools.data.ogr.jni.JniOGRDataStoreTest)  Time elapsed: 0.411 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.geotools.data.ogr.OGRDataStoreTest.testSchemaPop(OGRDataStoreTest.java:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Running org.geotools.data.ogr.jni.JniOGRPerformanceTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.068 sec - in org.geotools.data.ogr.jni.JniOGRPerformanceTest

Results :

Failed tests: 
  JniOGRDataStoreTest>OGRDataStoreTest.testShapefileComparison:203->OGRDataStoreTest.assertFeatureTypeEquals:269 null
  JniOGRDataStoreTest>OGRDataStoreTest.testOptimizedEnvelope:140 expected:<ReferencedEnvelope[-124.73142200000001 : -66.969849, 24.955967 : 49.371735] DefaultGeographicCRS[GCS_North_American_1983] AXIS["Longitude", EAST] AXIS["Latitude", NORTH]> but was:<ReferencedEnvelope[-124.73142200000001 : -66.969849, 24.955967 : 49.371735] DefaultGeographicCRS[EPSG:NAD83] AXIS["Latitude", NORTH] AXIS["Longitude", EAST]>
  JniOGRDataStoreTest>OGRDataStoreTest.testSchemaPop:109 null

Tests in error: 
  JniOGRDataStoreTest>OGRDataStoreTest.testAttributesWritingSqliteFromUpperCaseAttributes:753 » IO
  JniOGRDataStoreTest>OGRDataStoreTest.testAttributesWritingSqliteWithSorting:723 » IO
  JniOGRDataStoreTest>OGRDataStoreTest.testAttributesWritingSqlite:696 » IO OGR ...

Tests run: 36, Failures: 3, Errors: 3, Skipped: 0
```

**Comment by tbarsballe** [comment]
Now that we've got something mostly functional, some takeaways:

- A big part of the underlying issue is that setup-java was pulling an x64 JDK while the macos-latest runner is arm64
  - Java 11 JNI did not expose this issue, as it treated the mismatch like any other linking error. Java 21 had much better error-reporting
  - It [appears](https://github.com/actions/setup-java/issues/418#issuecomment-1338087314) setup-java@v3 autodetects architecture, while setup-java@v2 (which we are using), does not
  - Its possible macos-latest may have switched architectures at some point when the version it points to changed.
- imageio-ext-gdal is now running tests successfully: **Tests run: 33, Failures: 0, Errors: 0, Skipped: 8**. 
  - The other OS tests don't seem to be doing even this well (Tests run: 33, Failures: 0, Errors: 0, Skipped: 32) - we may want to revisit those.
- The (unsupported) ogr-jni module is incompatible with newer versions of GDAL (>= 3.3.0?), and is failing. vsi is likely in a similar state.

**Comment by rouault** [comment]
> * Its possible macos-latest may have switched architectures at some point when the version it points to changed.

it indeed changed to be an alias of macos-14 which is arm64 about 2 months ago or so (gave headaches to lots of folks)

**Comment by tbarsballe** [comment]
> > * Its possible macos-latest may have switched architectures at some point when the version it points to changed.
> 
> it indeed changed to be an alias of macos-14 which is arm64 about 2 months ago or so (gave headaches to lots of folks)

I'm kinda surprised the mac build continued to function at all after that, but I suppose without GDAL we weren't using any other native capabilities. Thanks for the confirmation of when the arch change happened.

File: modules/unsupported/ogr/ogr-jni/src/test/java/org/geotools/data/ogr/jni/JniOGRDataStoreTest.java [hunk 5]
```diff
@@ -1,10 +1,47 @@
...
 import org.geotools.data.ogr.OGRDataStoreTest;
+import org.junit.Ignore;
 
 public class JniOGRDataStoreTest extends OGRDataStoreTest {
 
     public JniOGRDataStoreTest() {
         super(JniOGRDataStoreFactory.class);
     }
+
+    @Ignore
```
Comment (tbarsballe) [inline modules/unsupported/ogr/ogr-jni/src/test/java/org/geotools/data/ogr/jni/JniOGRDataStoreTest.java]: Maybe it's just been a while and I'm doing it wrong, but `@Ignore` isn't working for some reason, no clue why.
Switching to just an empty `@Override`

**Comment by tbarsballe** [comment]
All tests are now passing, aside from a MySQL test suite that is also failing elsewhere

**Comment by jodygarnett** [comment]
thanks for the epic troubleshooting run
